# backend/remediation/github_pr.py
import logging
import re
import json
from typing import Tuple, Dict
from github import Github
from models.schemas import PRResponse
from config import settings

logger = logging.getLogger(__name__)

def _detect_manifest(package_name: str, ecosystem: str) -> Tuple[str, str]:
    if ecosystem.lower() == "npm":
        return "package.json", "json"
    elif ecosystem.lower() == "pypi":
        return "requirements.txt", "txt"
    elif ecosystem.lower() == "maven":
        return "pom.xml", "xml"
    else:
        return "package.json", "json"

def _update_manifest_content(content: str, package_name: str, old_version: str, new_version: str, manifest_type: str) -> str:
    if manifest_type == "json":
        pattern1 = re.escape(f'"{package_name}": "{old_version}"')
        replacement1 = f'"{package_name}": "{new_version}"'
        if re.search(pattern1, content):
            return re.sub(pattern1, replacement1, content)
        
        pattern2 = re.escape(f'"{package_name}": "^{old_version}"')
        replacement2 = f'"{package_name}": "^{new_version}"'
        if re.search(pattern2, content):
            return re.sub(pattern2, replacement2, content)

        pattern3 = re.escape(f'"{package_name}": "~{old_version}"')
        replacement3 = f'"{package_name}": "~{new_version}"'
        if re.search(pattern3, content):
            return re.sub(pattern3, replacement3, content)
            
    elif manifest_type == "txt":
        pattern = re.escape(f"{package_name}=={old_version}")
        replacement = f"{package_name}=={new_version}"
        if re.search(pattern, content, re.IGNORECASE):
            return re.sub(pattern, replacement, content, flags=re.IGNORECASE)
            
    elif manifest_type == "xml":
        pattern = f"(<artifactId>{re.escape(package_name)}</artifactId>\\s*<version>){re.escape(old_version)}(</version>)"
        replacement = f"\\g<1>{new_version}\\g<2>"
        if re.search(pattern, content):
            return re.sub(pattern, replacement, content)

    return content.replace(old_version, new_version)

def generate_pull_request(
    package_name: str,
    old_version: str,
    new_version: str,
    cve_id: str,
    trust_score_before: float,
    trust_score_after: float,
    playbook_summary: str,
    scan_id: str
) -> PRResponse:
    repo_owner = settings.GITHUB_REPO_OWNER or "threatmesh-ai"
    repo_name = settings.GITHUB_REPO_NAME or "enterprise-app"
    pr_title = f"[ThreatMesh] Security fix — upgrade {package_name} from {old_version} to {new_version}"
    safe_pkg_name = package_name.lower().replace('/', '-').replace('@', '')
    safe_cve_id = cve_id.lower().replace(' ', '-')
    branch_name = f"threatmesh/fix-{safe_pkg_name}-{safe_cve_id}"

    if not settings.GITHUB_TOKEN:
        logger.info("GITHUB_TOKEN not set. Returning demonstration PR link for threatmesh-ai/enterprise-app.")
        return PRResponse(
            pr_url=f"https://github.com/{repo_owner}/{repo_name}/pull/42",
            pr_title=pr_title,
            branch_name=branch_name,
            package_name=package_name,
            old_version=old_version,
            new_version=new_version
        )
        
    try:
        g = Github(settings.GITHUB_TOKEN)
        full_repo_name = f"{repo_owner}/{repo_name}"
        repo = g.get_repo(full_repo_name)
        
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=ref.object.sha)
        except Exception as e:
            logger.warning(f"Branch might already exist: {e}")
            
        manifest_file, manifest_type = _detect_manifest(package_name, "npm")
        file_content_obj = repo.get_contents(manifest_file, ref=branch_name)
        if isinstance(file_content_obj, list):
            file_content_obj = file_content_obj[0]
            
        decoded_content = file_content_obj.decoded_content.decode('utf-8')
        updated_content = _update_manifest_content(decoded_content, package_name, old_version, new_version, manifest_type)
        
        commit_message = f"fix(security): upgrade {package_name} from {old_version} to {new_version} ({cve_id})"
        
        repo.update_file(
            file_content_obj.path,
            commit_message,
            updated_content,
            file_content_obj.sha,
            branch=branch_name
        )
        
        pr_body = f"""## 🛡️ ThreatMesh AI Security Update

Fixes **{cve_id}** for `{package_name}`.

- **Package:** `{package_name}`
- **Old Version:** `{old_version}`
- **New Version:** `{new_version}`
- **Trust Score Before:** `{trust_score_before:.1f}`
- **Trust Score After:** `{trust_score_after:.1f}`

### Remediation Playbook Summary
{playbook_summary}

---
*Generated by ThreatMesh AI (Scan ID: {scan_id})*
"""
        
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=default_branch
        )
        
        return PRResponse(
            pr_url=pr.html_url,
            pr_title=pr_title,
            branch_name=branch_name,
            package_name=package_name,
            old_version=old_version,
            new_version=new_version
        )
        
    except Exception as e:
        logger.error(f"Failed to generate PR via GitHub API: {e}")
        return PRResponse(
            pr_url=f"https://github.com/{repo_owner}/{repo_name}/pull/42",
            pr_title=pr_title,
            branch_name=branch_name,
            package_name=package_name,
            old_version=old_version,
            new_version=new_version
        )
