import logging
from typing import Tuple
from github import Github
from models.schemas import PRResponse
from config import settings

logger = logging.getLogger(__name__)

def _detect_manifest(package_name: str, ecosystem: str) -> Tuple[str, str]:
    if ecosystem == "npm":
        return "package.json", "json"
    elif ecosystem == "pypi":
        return "requirements.txt", "txt"
    elif ecosystem == "maven":
        return "pom.xml", "xml"
    else:
        return "package.json", "json"

def _update_manifest(content: str, package_name: str, old_version: str, new_version: str, manifest_type: str) -> str:
    if manifest_type == "json":
        target = f'"{package_name}": "{old_version}"'
        replacement = f'"{package_name}": "{new_version}"'
        if target in content:
            return content.replace(target, replacement)
        
        target2 = f'"{package_name}": "^{old_version}"'
        replacement2 = f'"{package_name}": "^{new_version}"'
        if target2 in content:
            return content.replace(target2, replacement2)
            
    elif manifest_type == "txt":
        target = f"{package_name}=={old_version}"
        replacement = f"{package_name}=={new_version}"
        return content.replace(target, replacement)
        
    return content.replace(old_version, new_version)

def generate_pull_request(package_name: str, old_version: str, new_version: str, cve_id: str, 
                          trust_score_before: float, trust_score_after: float, 
                          playbook_summary: str, scan_id: str) -> PRResponse:
    if not settings.GITHUB_TOKEN:
        logger.warning("GITHUB_TOKEN not set. Returning mock PR response.")
        return PRResponse(
            pr_url="https://github.com/placeholder/repo/pull/1",
            pr_title=f"Security: Update {package_name} to {new_version} to fix {cve_id}",
            branch_name=f"threatmesh/fix-{package_name}-{cve_id}",
            package_name=package_name,
            old_version=old_version,
            new_version=new_version
        )
        
    try:
        g = Github(settings.GITHUB_TOKEN)
        repo_name = f"{settings.GITHUB_REPO_OWNER}/{settings.GITHUB_REPO_NAME}"
        repo = g.get_repo(repo_name)
        
        branch_name = f"threatmesh/fix-{package_name}-{cve_id}"
        
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=ref.object.sha)
        except Exception as e:
            logger.warning(f"Branch might already exist: {e}")
            
        ecosystem = "npm" # Defaulting for simplicity, in a real scenario we'd look it up or pass it in
        manifest_file, manifest_type = _detect_manifest(package_name, ecosystem)
        
        file_content = repo.get_contents(manifest_file, ref=branch_name)
        if isinstance(file_content, list):
            file_content = file_content[0]
            
        decoded_content = file_content.decoded_content.decode('utf-8')
        
        updated_content = _update_manifest(decoded_content, package_name, old_version, new_version, manifest_type)
        
        commit_message = f"chore(security): Bump {package_name} from {old_version} to {new_version}"
        
        repo.update_file(
            file_content.path,
            commit_message,
            updated_content,
            file_content.sha,
            branch=branch_name
        )
        
        pr_title = f"Security: Update {package_name} to {new_version} to fix {cve_id}"
        pr_body = f"""## Security Update for {package_name}

This PR fixes **{cve_id}**.

- **Package:** {package_name}
- **Old Version:** {old_version}
- **New Version:** {new_version}
- **Trust Score Before:** {trust_score_before}
- **Trust Score After:** {trust_score_after}

### Remediation Playbook Summary
{playbook_summary}

*Generated by ThreatMesh AI (Scan ID: {scan_id})*
"""
        
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=default_branch
        )
        
        return PRResponse(
            pr_url=pr.html_url,
            pr_title=pr_title,
            branch_name=branch_name,
            package_name=package_name,
            old_version=old_version,
            new_version=new_version
        )
        
    except Exception as e:
        logger.error(f"Failed to generate PR: {e}")
        raise ValueError(f"Failed to generate GitHub PR: {e}")
