import json
from models.schemas import Playbook
from agents import threat_agent, risk_agent, trust_agent, patch_agent, compliance_agent, safety_agent, governance_agent

async def run_council(context: dict) -> Playbook:
    try:
        from langgraph.graph import StateGraph
        HAS_LANGGRAPH = True
    except ImportError:
        HAS_LANGGRAPH = False

    # For simplicity and robust fallback, we use sequential execution
    threat_res = await threat_agent.run(context)
    risk_res = await risk_agent.run(context)
    trust_res = await trust_agent.run(context)
    patch_res = await patch_agent.run(context)
    compliance_res = await compliance_agent.run(context)
    safety_res = await safety_agent.run(context)
    governance_res = await governance_agent.run(context)

    confidence = 75.0 # default

    playbook = Playbook(
        scan_id=context.get("scan_id", "unknown"),
        package_name=context.get("package_name", "unknown"),
        threat_summary=json.dumps(threat_res),
        business_impact=json.dumps(risk_res),
        trust_explanation=json.dumps(trust_res),
        recommended_action=json.dumps(patch_res),
        compliance_mapping=compliance_res,
        confidence_score=confidence,
        evidence_citations=["Generated by AI Council"]
    )
    return playbook
